# Generated by Django 2.1.7 on 2019-03-22 18:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('courses', '0016_auto_20190322_1448'),
        ('quiz', '0002_auto_20190320_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizBank',
        ),
    ]
