# Generated by Django 2.1.7 on 2019-03-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190322_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizbank',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
        ),
    ]
