# Generated by Django 2.1.7 on 2019-03-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190322_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizbank',
            old_name='required_score',
            new_name='pass_rate',
        ),
        migrations.AddField(
            model_name='quizbank',
            name='required_questions_num',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
