# Generated by Django 2.1.7 on 2019-03-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20190324_0658'),
        ('quiz', '0006_auto_20190323_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizbank',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
