# Generated by Django 2.1.7 on 2019-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_component_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
