# Generated by Django 2.1.7 on 2019-03-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_component_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='module',
        ),
    ]
