# Generated by Django 2.1.7 on 2019-03-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_component_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
            preserve_default=False,
        ),
    ]
