# Generated by Django 2.1.7 on 2019-03-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_component_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
        ),
    ]
