# Generated by Django 2.1.7 on 2019-03-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190320_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Module'),
        ),
    ]
