# Generated by Django 2.1.7 on 2019-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190322_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('completed_modules', models.ManyToManyField(to='courses.Module')),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
