# Generated by Django 2.1.7 on 2019-03-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
