# Generated by Django 2.1.7 on 2019-03-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190323_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, to='courses.Module'),
        ),
    ]
