# Generated by Django 2.1.7 on 2019-03-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190323_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
