# Generated by Django 2.1.7 on 2019-03-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_component_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
