# Generated by Django 2.1.7 on 2019-03-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20190324_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
