# Generated by Django 2.1.7 on 2019-03-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
            preserve_default=False,
        ),
    ]
