# Generated by Django 2.1.7 on 2019-03-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20190326_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
    ]
