# Generated by Django 2.1.7 on 2019-04-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20190326_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
