# Generated by Django 2.1.7 on 2019-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_remove_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_units',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
