# Generated by Django 2.1.7 on 2019-04-03 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0033_auto_20190401_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_learner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
