# Generated by Django 2.1.7 on 2019-04-03 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0034_course_current_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='current_learner',
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
