# Generated by Django 2.1.7 on 2019-04-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20190403_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
