# Generated by Django 2.1.7 on 2019-04-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20190403_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='learner',
            name='last_name',
            field=models.CharField(db_index=True, default='Chan', max_length=50),
            preserve_default=False,
        ),
    ]
