# Generated by Django 2.1.7 on 2019-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20190404_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='staff_id',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
