# Generated by Django 2.1.7 on 2019-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_auto_20190404_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
