# Generated by Django 2.1.7 on 2019-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_learner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
