# Generated by Django 2.1.7 on 2019-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20190406_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(db_index=True, default='Arthur', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(db_index=True, default='Morgan', max_length=50),
            preserve_default=False,
        ),
    ]
