# Generated by Django 2.2 on 2019-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20190408_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(db_index=True, default='IT', max_length=150),
            preserve_default=False,
        ),
    ]
