# Generated by Django 2.2 on 2019-04-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_learner_completed_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='completed_courses',
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Learner')),
            ],
        ),
    ]
