# Generated by Django 2.2 on 2019-04-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_auto_20190408_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletion',
            name='cumulative_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
