# Generated by Django 2.2 on 2019-04-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_auto_20190426_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
        ),
    ]
