# Generated by Django 2.1.7 on 2019-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190319_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='title',
            field=models.TextField(default='First Component', max_length=50),
            preserve_default=False,
        ),
    ]
