# Generated by Django 2.1.7 on 2019-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190319_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
